spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
    hikari:
      connection:
        init-sql: data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init.mode: always