create table CATEGORY
(
    ID          INTEGER GENERATED BY DEFAULT AS IDENTITY
        primary key,
    NAME        CHARACTER VARYING(255),
    DESCRIPTION CHARACTER VARYING(255)
);
create table PRODUCT
(
    ID          INTEGER GENERATED BY DEFAULT AS IDENTITY
        primary key,
    NAME        CHARACTER VARYING(255),
    PRICE       DOUBLE PRECISION,
    DESCRIPTION CHARACTER VARYING(255),
    CATEGORY_ID INTEGER,
    constraint PRODUCT_CATEGORY_FK
        foreign key (CATEGORY_ID) references CATEGORY
);
INSERT INTO CATEGORY (name, description) VALUES ('Electronics', 'Devices and gadgets');
INSERT INTO CATEGORY (name, description) VALUES ('Clothing', 'Apparel and accessories');
INSERT INTO CATEGORY (name, description) VALUES ('Home & Kitchen', 'Furniture and kitchenware');
INSERT INTO CATEGORY (name, description) VALUES ('Books', 'Printed and digital books');
INSERT INTO CATEGORY (name, description) VALUES ('Sports & Outdoors', 'Sporting goods and outdoor equipment');
INSERT INTO CATEGORY (name, description) VALUES ('Beauty & Personal Care', 'Cosmetics and personal care products');
INSERT INTO CATEGORY (name, description) VALUES ('Toys & Games', 'Children’s toys and games');
INSERT INTO CATEGORY (name, description) VALUES ('Automotive', 'Car parts and accessories');
INSERT INTO CATEGORY (name, description) VALUES ('Health & Wellness', 'Health products and supplements');
INSERT INTO CATEGORY (name, description) VALUES ('Office Supplies', 'Stationery and office equipment');
INSERT INTO product (name, price, description, category_id) VALUES ('Smartphone', 699.99, 'Latest model smartphone with advanced features.', 1);
INSERT INTO product (name, price, description, category_id) VALUES ('Laptop', 999.99, 'High-performance laptop for gaming and work.', 1);
INSERT INTO product (name, price, description, category_id) VALUES ('Wireless Headphones', 199.99, 'Noise-cancelling over-ear headphones.', 1);
INSERT INTO product (name, price, description, category_id) VALUES ('Digital Camera', 499.99, 'Compact camera with high-resolution capabilities.', 1);
INSERT INTO product (name, price, description, category_id) VALUES ('T-shirt', 19.99, 'Cotton t-shirt available in various colors.', 2);
INSERT INTO product (name, price, description, category_id) VALUES ('Jeans', 39.99, 'Stylish denim jeans for casual wear.', 2);
INSERT INTO product (name, price, description, category_id) VALUES ('Jacket', 89.99, 'Warm winter jacket with a stylish design.', 2);
INSERT INTO product (name, price, description, category_id) VALUES ('Sneakers', 59.99, 'Comfortable sneakers for everyday use.', 2);
INSERT INTO product (name, price, description, category_id) VALUES ('Sofa', 399.99, 'Comfortable sofa for living room.', 3);
INSERT INTO product (name, price, description, category_id) VALUES ('Dining Table', 299.99, 'Elegant dining table made of solid wood.', 3);